apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stateless-webapp.fullname" . }}
  labels:
    app: {{ include "stateless-webapp.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "stateless-webapp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "stateless-webapp.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          env:
            - name: APP_ENV
              value: {{ .Values.env.APP_ENV | quote }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
              